"""Central configuration for the Job Posting Radar application."""

from datetime import date
from pathlib import Path

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class AppSettings(BaseSettings):
    """Application configuration loaded from environment variables or defaults."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    data_dir: Path = Field(
        default_factory=lambda: Path("data"),
        description="Base directory for local artifacts.",
    )
    raw_subdir: str = Field(
        default="raw",
        description="Subdirectory under data_dir for raw payload storage.",
    )
    nofluff_base_url: str = Field(
        default="https://nofluffjobs.com",
        description="Base URL for No Fluff Jobs website.",
    )
    nofluff_timeout_seconds: float = Field(
        default=30.0,
        description="HTTP request timeout for No Fluff Jobs requests.",
    )
    nofluff_rate_limit_seconds: float = Field(
        default=1.0,
        description="Minimum seconds between outbound requests to respect rate limits.",
    )
    request_max_retries: int = Field(
        default=3,
        description="Number of retries for transient HTTP failures.",
    )
    backoff_initial_seconds: float = Field(
        default=1.0,
        description="Base backoff delay in seconds for retry attempts.",
    )
    backoff_multiplier: float = Field(
        default=2.0,
        description="Multiplier applied to backoff after each retry.",
    )
    nofluff_search_path: str = Field(
        default="/api/joboffers/main",
        description="Path for the No Fluff Jobs listing XHR endpoint.",
    )
    nofluff_posting_path: str = Field(
        default="/api/posting",
        description="Path for the No Fluff Jobs posting detail endpoint.",
    )
    nofluff_page_size: int = Field(
        default=20,
        description="Number of offers to request per page from No Fluff Jobs.",
    )
    nofluff_region: str = Field(
        default="pl",
        description="Region parameter sent to No Fluff Jobs search endpoint.",
    )
    nofluff_language: str = Field(
        default="en-GB",
        description="Language parameter sent to No Fluff Jobs search endpoint.",
    )
    nofluff_salary_currency: str = Field(
        default="PLN",
        description="Salary currency filter for No Fluff Jobs search.",
    )
    nofluff_salary_period: str = Field(
        default="month",
        description="Salary period filter for No Fluff Jobs search.",
    )
    justjoin_base_url: str = Field(
        default="https://justjoin.it",
        description="Base URL for Just Join IT.",
    )
    justjoin_api_base_url: str = Field(
        default="https://api.justjoin.it",
        description="API base URL for Just Join IT.",
    )
    justjoin_api_offers_path: str = Field(
        default="/api/offers",
        description="API path for Just Join IT offers.",
    )
    justjoin_page_size: int = Field(
        default=100,
        description="Number of offers to request per page from Just Join IT.",
    )
    qdrant_host: str = Field(
        default="localhost",
        description="Host for Qdrant vector database.",
    )
    qdrant_port: int = Field(
        default=6333,
        description="Port for Qdrant vector database API.",
    )
    qdrant_collection_name: str = Field(
        default="job_posts",
        description="Name of the Qdrant collection for job postings.",
    )
    pushgateway_host: str = Field(
        default="localhost",
        description="Host for Prometheus Pushgateway.",
    )
    pushgateway_port: int = Field(
        default=9091,
        description="Port for Prometheus Pushgateway.",
    )
    embedding_model_name: str = Field(
        default="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
        description="HuggingFace model name for generating embeddings.",
    )
    embedding_dimension: int = Field(
        default=384,
        description="Dimension of the vectors generated by the embedding model.",
    )
    user_agent: str = Field(
        default="job-posting-radar/ingest",
        description="User agent sent to upstream sources.",
    )

    def raw_root(self) -> Path:
        """Return the root directory for raw payloads.

        Returns:
            Path to the raw data root directory.
        """
        return self.data_dir / self.raw_subdir

    def source_raw_dir(self, source: str, target_date: date) -> Path:
        """Return the directory where raw payloads for a source and date should be stored.

        Args:
            source: Data source identifier (e.g., "nofluff", "justjoin").
            target_date: Target date for the data.

        Returns:
            Path to the source-specific raw data directory.
        """
        return self.raw_root() / source / target_date.isoformat()
